# Generated by Django 2.1.5 on 2019-01-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(default='', verbose_name='Event Date')),
                ('venue', models.CharField(default='', max_length=120)),
                ('manager', models.CharField(default='', max_length=60)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
