# Generated by Django 2.1.5 on 2019-01-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ('b_hash',)},
        ),
        migrations.RemoveField(
            model_name='block',
            name='description',
        ),
        migrations.RemoveField(
            model_name='block',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='block',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='block',
            name='name',
        ),
        migrations.RemoveField(
            model_name='block',
            name='venue',
        ),
        migrations.AddField(
            model_name='block',
            name='b_hash',
            field=models.TextField(default='', max_length=2048, verbose_name='Block Hash'),
        ),
        migrations.AddField(
            model_name='block',
            name='p_hash',
            field=models.TextField(default='', max_length=2048, verbose_name='Previous Hash'),
        ),
    ]
