# Generated by Django 2.1.5 on 2019-01-27 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20190125_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.IntegerField(default=20, verbose_name='reward')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='block_chain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='metrics.BlockChain'),
        ),
    ]
