# Generated by Django 2.1.5 on 2019-01-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_auto_20190127_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_hash', models.TextField(default='', max_length=2048, verbose_name='Transaction hash')),
            ],
        ),
    ]
