# Generated by Django 2.1.5 on 2019-02-03 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_hash', models.TextField(default='', max_length=2048, verbose_name='Wallet Address')),
                ('amount', models.TextField(default=0, verbose_name='Wallet amount')),
            ],
            options={
                'ordering': ('wallet_hash',),
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='metrics.Wallet'),
        ),
    ]
